### ISSUE TITLE
Tekst ved ingen hendelser

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMkalender#6]
Hvis det ikke er lagt til kalenderhendelser må denne få forklarende tekst

**Comment by AsgeirSH** [comment]
Fixed by Twigging:
![skjermbilde 2016-09-05 kl 11 05 02](https://cloud.githubusercontent.com/assets/1831028/18242858/a3cae50c-7358-11e6-8c3f-58557bd9c285.png)
